email:
  password: ''
  smtp_port: 587
  smtp_server: smtp.gmail.com
  user: ''
human_in_the_loop:
  daily_analysis_time: 08:00
  email_recipient: your-email@example.com
  max_markets: 10
  min_confidence: 5
  min_edge: 0.05
  web_interface_host: 127.0.0.1
  web_interface_port: 5000
research:
  cache_hours: 24
  cost_per_call: 0.17
  max_retries: 3
trading:
  max_days_to_resolution: 90
  max_position_size: 0.2
  max_total_allocation: 0.8
  min_days_to_resolution: 1
  min_volume_24h: 1000
